/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lmy_ffmpeg_Tool */

#define NULL 0
#ifndef _Included_com_lmy_ffmpeg_Tool
#define _Included_com_lmy_ffmpeg_Tool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lmy_ffmpeg_Tool
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lmy_ffmpeg_Tool_version
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
