/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lmy_ffmpeg_player_Player */

#ifndef _Included_com_lmy_ffmpeg_player_Player
#define _Included_com_lmy_ffmpeg_player_Player
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lmy_ffmpeg_player_Player
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_lmy_ffmpeg_player_Player_decode
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
