/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lmy_ffmpeg_codec_MediaDecoder */

#ifndef _Included_com_lmy_ffmpeg_codec_MediaDecoder
#define _Included_com_lmy_ffmpeg_codec_MediaDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lmy_ffmpeg_codec_MediaDecoder
 * Method:    decode
 * Signature: (Ljava/lang/String;Lcom/lmy/ffmpeg/codec/AVFrame;)V
 */
JNIEXPORT void JNICALL Java_com_lmy_ffmpeg_codec_MediaDecoder_decode
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
